<?php

require_once '../../test-jednostkowe/Pogoda.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-17 at 01:33:40.
 */
class PogodaTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Pogoda
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Pogoda;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Pogoda::deszcz
	 * @todo   Implement testDeszcz().
	 */
	public function testDeszcz() {
		$expected = true;
		$received = $this->object->deszcz();
		$this->assertEquals($expected, $received);
	}

	/**
	 * @covers Pogoda::snieg
	 * @todo   Implement testSnieg().
	 */

}
