<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-17 at 18:21:15.
 */
class PogodaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Pogoda
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Pogoda;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Pogoda::deszcz
     * @todo   Implement testDeszcz().
     */
    public function testDeszcz() {
        $this->assertTrue($this->object->deszcz());
    }

    /**
     * @covers Pogoda::snieg
     * @todo   Implement testSnieg().
     */
    public function testSnieg() {
       $this->assertFalse($this->object->snieg());
    }

    /**
     * @covers Pogoda::temperatura
     * @todo   Implement testTemperatura().
     */
    public function testTemperatura() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
